### ISSUE TITLE
convert parse tree into a pure dictionray

### ISSUE THREAD

**Issue by priamai** [brettforbes/stix_patterns#2]
This is not a dictionary but a nested object.
https://github.com/brettforbes/stix_patterns/blob/11954e6514f67249123398fb978e1ad40cb09950/make_observations.py#L188
It needs to be converted/serialized into a dictionary.

**Comment by andrewgin** [comment]
It is currently nested dicts;
What is the desired representation of the following?
```
pattern:
  observation:
    objects: {domain-name}
    join:
    qualifiers:
    expressions:
      - comparison:
          object: domain-name
          path: [value]
          negated:
          operator: '='
          value: site.of.interest.zaz
```
